spring:
  datasource:
    url: jdbc:h2:mem:taskdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  security:
    enabled: true

emailregex: "^[A-Za-z0-9+_.-]+@[a-zA-Z0-9.-]+$"
passwordregex: "^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d{2,}).{6,}$"